export const CART_ADD_PRODUCT = "CART_ADD_PRODUCT";
export const CART_INCREMENT_PRODUCT_QUANTITY =
  "CART_INCREMENT_PRODUCT_QUANTITY";
export const CART_DECREMENT_PRODUCT_QUANTITY =
  "CART_DECREMENT_PRODUCT_QUANTITY";
export const FAVOURITE_ADD_PRODUCT = "FAVOURITE_ADD_PRODUCT";
export const CART_DELETE_PRODUCT = "CART_DELETE_PRODUCT;";
export const FAVOURITE_DELETE_PRODUCT = "FAVOURITE_DELETE_PRODUCT";
export const RESET_BASKET = "RESET_BASKET";
